language: python
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper autotools-dev cups-ppdc libcups2-dev cups python-cups python-httplib2 imagemagick
 - pip install httplib2 pycups pytest-cov --use-mirrors
install:
 - ./configure
 - sudo gpasswd -a `whoami` lpadmin
 - sudo gpasswd -a `whoami` lp
 - sudo make install
 - sudo cupsctl --debug-logging
 - sudo cp .coveragerc /usr/local/share/cloudprint-cups/
 - sudo cp testfiles/testppd.ppd  /usr/share/cups/model/testppd.ppd
script:
 - cd /usr/local/share/cloudprint-cups/
 - sudo chmod 777 .
 - sudo chmod o+rw testfiles
 - sudo ./upgrade.py
 - sudo python -m compileall .
 - py.test --cov .
 - sudo cat /var/log/cups/cloudprint_log /var/log/cups/error_log
 - sudo unlink /usr/share/cups/model/testppd.ppd
after_success:
 - curl -d "github-repo=$TRAVIS_REPO_SLUG" -d "commit=$TRAVIS_COMMIT" -d "python-version=$TRAVIS_PYTHON_VERSION" -d "job-number=$TRAVIS_JOB_NUMBER" utils.niftiestsoftware.com/buildpackage/successful-build.php